name: Test Collector
description: Uploads your JSON or JUnit files to Buildkite Test Analytics
author: https://github.com/buildkite
requirements:
  - docker
  - curl
configuration:
  properties:
    api-token-env-name:
      type: string
    debug:
      type: boolean
    files:
      type: string
    format:
      enum:
        - json
        - junit
    timeout:
      type: integer
  required:
    - files
    - format
  additionalProperties: false
